name: vlb
channels:
- conda-forge
- anaconda
- menpo
- defaults
dependencies:
- python=3.4
- blas
- scipy
- bzip2
- openblas
- matplotlib
- numpy
- tqdm
- cyvlfeat
- opencv
- vlfeat
- pip:
  - exifread
  - h5py
  - hickle
  - pybind11
  - nmslib
  - pipreqs
